version: "3.7"
services:
    mysql-server:
        build:
            dockerfile: mysql.Dockerfile
            context: .
        container_name: mysql-server
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: f1
            MYSQL_DATABASE: ergastdb
        ports:
            - "3306:3306"
