version: "3.7"
services:
    # TODO: use for production builds
    # api-server:
    #   build:
    #     dockerfile: apiServer.Dockerfile
    #     context: .
    #   container_name: api-server
    #   restart: always
    #   environment:
    #     NODE_ENV: production
    #   ports:
    #     - "8080:8732"

    mysql-server:
        build:
            dockerfile: mysql.Dockerfile
            context: .
        container_name: mysql-server
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: f1
            MYSQL_DATABASE: ergastdb
        ports:
            - "3306:3306"
